// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftPost = `-- name: CreateDraftPost :one
insert into posts ( title, excerpt, content_md, status, user_id, published_at )
values ( $1, $2, $3, 'draft', $4, null)
returning id, title, excerpt, content_md, status, user_id, published_at, created_at, updated_at
`

type CreateDraftPostParams struct {
	Title     string
	Excerpt   pgtype.Text
	ContentMd string
	UserID    pgtype.UUID
}

func (q *Queries) CreateDraftPost(ctx context.Context, arg CreateDraftPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createDraftPost,
		arg.Title,
		arg.Excerpt,
		arg.ContentMd,
		arg.UserID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Excerpt,
		&i.ContentMd,
		&i.Status,
		&i.UserID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPosts = `-- name: GetAllPosts :many
select id, title, excerpt, content_md, status, user_id, published_at, created_at, updated_at from posts where status = 'published'
order by published_at desc
LIMIT $2 OFFSET $1
`

type GetAllPostsParams struct {
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) GetAllPosts(ctx context.Context, arg GetAllPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getAllPosts, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.ContentMd,
			&i.Status,
			&i.UserID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostById = `-- name: GetPostById :one
select id, title, excerpt, content_md, status, user_id, published_at, created_at, updated_at from posts where id = $1 and status = 'published'
`

func (q *Queries) GetPostById(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Excerpt,
		&i.ContentMd,
		&i.Status,
		&i.UserID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
