// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users(email, hash_pw)
values ($1, $2)
returning id
`

type CreateUserParams struct {
	Email  string
	HashPw string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.HashPw)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
